[Variables]
; =========
;   Title
; =========
TitleSize=50

TitleFont=Moon flower bold

TitleColor=255,255,255
; In RGB format (No alpha)

TitleAlign=Center
; The title position (Left, Center or Right)


; =========
;   Icons
; =========
IconSize=40

IconSpacing=8
; The gap between icons

IconColor=255,255,255
; In RGB format (No alpha)


; =============
;   Animation
; =============
AnimAlign=Center
; The animation start position (Left, Center or Right)

AnimDuration=300
; The total time for the animation (milliseconds)

AnimInterval=30
; The time between animations of icons  (milliseconds)
; (Set a value more than 0 to animate the icons sequentially)

AnimEasing=InQuad
; The easing used for the animations. 
; For the full list of easings, visit https://easings.net
; (At the website, if you want to use, say 'easeInQuint', type 'inQuint' (without quotes) instead)


; =========
;   Others
; =========
SkinPadding=20
; The space around the skin for easier mouse detection