[LineTopStyle]
Group=Tweenable
X=(-#LineSpacing# - #LineHorLength#)r
Y=#LineMove#
W=#LineHorLength#
H=#LineThickness#
SolidColor=#ForegroundColor#

[LineLeftStyle]
Group=Tweenable
X=#LineMove#
Y=#LineSpacing#R
W=#LineThickness#
H=#LineVerLength#
SolidColor=#ForegroundColor#

[LineBottomStyle]
Group=Tweenable
X=#LineSpacing#R
Y=(#WindowHeight# - #LineMove# - #LineThickness#)
W=#LineHorLength#
H=#LineThickness#
SolidColor=#ForegroundColor#

[LineRightStyle]
Group=Tweenable
X=(#WindowWidth# - #LineMove# - #LineThickness#)
Y=(-#LineSpacing# - #LineVerLength#)r
W=#LineThickness#
H=#LineVerLength#
SolidColor=#ForegroundColor#



[LineTopLayoutOffset]
Meter=Image
X=(#WindowWidth# + #LineSpacing#)

[Line0]
Meter=Image
MeterStyle=LineTopStyle

[Line1]
Meter=Image
MeterStyle=LineTopStyle

[Line2]
Meter=Image
MeterStyle=LineTopStyle

[Line3]
Meter=Image
MeterStyle=LineTopStyle

[Line4]
Meter=Image
MeterStyle=LineTopStyle

[Line5]
Meter=Image
MeterStyle=LineTopStyle

[Line6]
Meter=Image
MeterStyle=LineTopStyle

[Line7]
Meter=Image
MeterStyle=LineTopStyle

[Line8]
Meter=Image
MeterStyle=LineTopStyle

[Line9]
Meter=Image
MeterStyle=LineTopStyle


[LineLeftLayoutOffset]
Meter=Image
Y=(-#LineSpacing#)

[Line10]
Meter=Image
MeterStyle=LineLeftStyle

[Line11]
Meter=Image
MeterStyle=LineLeftStyle

[Line12]
Meter=Image
MeterStyle=LineLeftStyle

[Line13]
Meter=Image
MeterStyle=LineLeftStyle

[Line14]
Meter=Image
MeterStyle=LineLeftStyle

[Line15]
Meter=Image
MeterStyle=LineLeftStyle

[Line16]
Meter=Image
MeterStyle=LineLeftStyle

[Line17]
Meter=Image
MeterStyle=LineLeftStyle

[Line18]
Meter=Image
MeterStyle=LineLeftStyle

[Line19]
Meter=Image
MeterStyle=LineLeftStyle


[LineBottomLayoutOffset]
Meter=Image
X=(-#LineSpacing#)

[Line20]
Meter=Image
MeterStyle=LineBottomStyle

[Line21]
Meter=Image
MeterStyle=LineBottomStyle

[Line22]
Meter=Image
MeterStyle=LineBottomStyle

[Line23]
Meter=Image
MeterStyle=LineBottomStyle

[Line24]
Meter=Image
MeterStyle=LineBottomStyle

[Line25]
Meter=Image
MeterStyle=LineBottomStyle

[Line26]
Meter=Image
MeterStyle=LineBottomStyle

[Line27]
Meter=Image
MeterStyle=LineBottomStyle

[Line28]
Meter=Image
MeterStyle=LineBottomStyle

[Line29]
Meter=Image
MeterStyle=LineBottomStyle


[LineRightLayoutOffset]
Meter=Image
Y=(#WindowHeight#+#LineSpacing#)

[Line30]
Meter=Image
MeterStyle=LineRightStyle

[Line31]
Meter=Image
MeterStyle=LineRightStyle

[Line32]
Meter=Image
MeterStyle=LineRightStyle

[Line33]
Meter=Image
MeterStyle=LineRightStyle

[Line34]
Meter=Image
MeterStyle=LineRightStyle

[Line35]
Meter=Image
MeterStyle=LineRightStyle

[Line36]
Meter=Image
MeterStyle=LineRightStyle

[Line37]
Meter=Image
MeterStyle=LineRightStyle

[Line38]
Meter=Image
MeterStyle=LineRightStyle

[Line39]
Meter=Image
MeterStyle=LineRightStyle