[Variables]
TitleName=My Stuff

IconCount=5
; Please specify this according to the number of icons listed

; Note:
; The images must be kept in @Resources/Images if you want 
; to specify the relative icon image path like below

Icon1=PC.png
Path1=explorer

Icon2=setting.png
Path2=ms-settings:

Icon3=music.png
Path3=

Icon4=photo.png
Path4=shell:appsFolder\Microsoft.Windows.Photos_8wekyb3d8bbwe!App

Icon5=office.png
Path5=
